spring:
    sql:
      init:
          mode: always
    datasource:
        url: jdbc:h2:tcp://localhost/~/hanseoVill
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true

    jwt:
        header: Authorization
        secret: ZGQ5MDY4ODktYTAzNS00MzhjLWI3ZjMtZTk3NzEwOTI2MzFj
        token-validity-in-seconds: 86400


logging:
    level:
        org.hibernate.SQL: debug